version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  parse-server:
    build: .
    container_name: note-taking-app-server
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - PARSE_SERVER_DATABASE_URI=mongodb://mongodb:27017/dev
      - PARSE_SERVER_APPLICATION_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_SERVER_MASTER_KEY=${PARSE_SERVER_MASTER_KEY}
      # - PARSE_SERVER_CLOUD=${PARSE_SERVER_CLOUD}
      - PARSE_SERVER_URL=${PARSE_SERVER_URL}
    volumes:
      - .:/app   # Mount the local directory for hot-reloading with nodemon
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/parse"]
      interval: 30s
      timeout: 10s
      retries: 5
